version: '3'

services:

  api:
    container_name: memberstack-api
    build: ./api
    env_file:
      - api.env
    # environment:
      # - DB_ADDRESS=mongo
    ports:
      - 8000:8000

  fe:
    container_name: memberstack-fe
    build: ./fe
    env_file:
      - fe.env
    ports:
      - 3000:3000

  db:
    image: mongo
    container_name: memberstack-mongo
    ports:
      - 27017:27017
