FROM node:12.16.1

# Define the working directory
WORKDIR /usr/app

# Copy package and package lock
COPY package*.json ./

# Install node dependencies
RUN npm install && npm install tsc -g

# Put all files in the current directory into the workdir of the image
COPY . .

# Compile typescript
RUN npm run build

CMD ["node", "./build/src/index.js"]
